# Generated by Django 5.1.7 on 2025-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=400)),
                ('q2', models.CharField(max_length=500)),
                ('q3', models.CharField(max_length=500)),
                ('q4', models.CharField(max_length=500)),
                ('q5', models.TextField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.CharField(max_length=555)),
                ('q9', models.CharField(max_length=500)),
            ],
        ),
    ]
